### ISSUE TITLE
plugin version

### ISSUE THREAD

**Issue by diminutivesloop** [donmckenna/scully-docs-navlist-redesign#1]
Hey are there any plans to develop this into a Scully plugin? I'm building a docs site for an Angular library w/ Scully and I'll probably adapt this code but if there's a plugin I'd rather just use that.

**Comment by donmckenna** [comment]
Plans? Yes. 
Idea of when/if the plans will be realized? Not sure unfortunately.

The Scully core team updated the code since this version, so I'm not sure exactly how many aspects changed in the actual Scully repo if you were looking.

I'd love to make this into a standalone plugin for these exact purposes, it just depends on my (lack of) free time at the moment.
But now that you've brought it up, it's a good idea and I'll think more seriously about actually building a plugin for nested navigation.
